version: '3.8'

services:
  app:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV:-development}
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - ./configs/.production.env

  db:
    image: mongo:4.4
    volumes:
      - dbdata:/data/db
    ports:
      - '27017:27017'

volumes:
  dbdata:
